import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Slider from "rc-slider";
import "rc-slider/assets/index.css";
import { useState } from "react";
import TreeLoader from "../components/TreeLoader";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [progress, setProgress] = useState(20);

  return (
    <div className={styles.container}>
      <Head>
        <title>Rive Progress Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rive Progress Test</h1>
        <div style={{ width: "70%", maxWidth: 600 }}>
          <div style={{ textAlign: "center", margin: "30px 0 10px" }}>
            Progress:{" "}
            <span
              style={{
                display: "inline-block",
                padding: "2px 5px",
                backgroundColor: "#F4F4F4",
                fontWeight: "bold",
              }}
            >
              {progress}
            </span>
          </div>
          <Slider
            onChange={(nextValue) => setProgress(nextValue as number)}
            value={progress}
            min={0}
            max={100}
            step={1}
            railStyle={{ height: 14 }}
            trackStyle={{ height: 14 }}
            handleStyle={{
              height: 40,
              width: 40,
              marginLeft: 0,
              marginTop: -13,
            }}
          />
        </div>
        <div style={{ height: 300, width: "100%" }}>
          <TreeLoader progress={progress} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
